#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 13 20:11:56 2016

@author: Pranavtadepalli
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 21 21:20:25 2016

@author: Pranavtadepalli
"""

import PIL
import math
im=PIL.Image.new('RGB', (500,500))
def convert(c):
    c=c.strip('(')
    c=c.strip(')')
    r=c.split('+')
    n=[0,0]
    for l in r:
        if len(l.split('j'))==2:
            try:
                n[1]=int(l.split('j')[0])
            except:
                pass
        else:
            try:
                n[0]=int(l)
            except:
                pass
    return(n)
print(convert('(-21+54j)'))

def fun(x,y):
    try:
        lo=round(abs(math.sqrt(x+y)))
        z=complex(x,y)
        
        while lo<abs(x-y):
            z=z**2+complex(x,y)+y*4
            lo=lo+1
        t=[(convert(str(z))[0],convert(str(z))[1],50)]
        return(t)
        
    except:
       print('error')

x=0
y=0
nz=1
for x in range(500):
    for y in range(500):
       try:
            im.putpixel((x,y),fun(x,y)[0])
       except:
            print('error1')
im.show()