#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb 12 14:22:19 2017

@author: Pranavtadepalli
"""
listy=[]

def pan(w):
    f=''
    e=0
    while True:
        e=e+1
        f=f+str(w*e)
        if len(f)>=9:
            break
    return(str(f))
for w in range(1000000):
    var=pan(w)
    if len(set(list(var)))==9 and len(var)==9 and len(var.split('0'))<2:
        listy.append(int(var))
print(max(listy))