#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 27 08:02:43 2017

@author: Pranavtadepalli
"""
q=0
loop=-1
while q==0:
    listy=[]
    loop=loop+1
    hi=0
    for elem in range(6):
        hi=hi+1
        listy.append(loop*hi)
    sety=[set(list(str(a))) for a in listy]
    if sety.count(sety[0]) == len(sety):
        print("found: ",loop)
        
    