#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 20 16:22:15 2017

@author: Pranavtadepalli
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 19 13:16:33 2017

@author: Pranavtadepalli
"""
#'"id","qid1","qid2","question1","question2","is_duplicate"'
import csv
from fuzzywuzzy import fuzz
from stop_words import get_stop_words
stopwords=get_stop_words('en')
def function(q1,q2):
    q1=' '.join([q for q in q1.split(' ') if q not in stopwords])
    q2=' '.join([q for q in q2.split(' ') if q not in stopwords])
    try:
        if fuzz.ratio(q1, q2)>58:
            return 1
        else:
            return 0
    except:
        return 0
final=[]
final1=[]
time=1
with open('train.csv', newline='\n',encoding='UTF-8') as f:
    reader = csv.reader(f)
    for elem in reader:
        final1.append(1)
        if time==0:
            result=function(elem[3],elem[4])
            if str(result)==str(elem[5]):
                final.append(1)
        else:
            time=0
print(len(final)/len(final1))