#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov  5 18:01:09 2016

@author: Pranavtadepalli
"""


from random import choice
from PyDictionary import PyDictionary
dictionary=PyDictionary()
from random_words import RandomWords
rw = RandomWords()
words=rw.random_words(count=10)
for el in words:

    defi=dictionary.meaning(el)
    print(list(defi.items())[0][0])