#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov 26 15:02:08 2016

@author: Pranavtadepalli
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov 26 12:03:29 2016

@author: Pranavtadepalli
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov 26 09:14:21 2016

@author: Pranavtadepalli
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 25 10:22:14 2016

@author: Pranavtadepalli
"""

#from PIL import Image, ImageTk
import tkinter
import time
from tkinter import messagebox
import random
t=0
#a=time.time()
a=0
def funny(coo):
    print(coo)
    coo=str(coo)
    hee=eval('a'+coo[0]+coo[1])
    hee.config(image=img1)
    hee=eval('a'+random.choice(['0','1','2','3'])+random.choice(['0','1','2','3']))
    hee.config(image=img)

    
root = tkinter.Toplevel()
#root.geometry('{}x{}'.format(1000, 1000))
img = tkinter.PhotoImage(file='dead.gif')
img1 = tkinter.PhotoImage(file='really.gif')
tee=-1
are=random.randint(0,16)
for r in range(4):
    for c in range(4):
        tee=tee+1
        if tee==are: 
            po=(str(r)+str(c))
            print(po)
            exec('a'+str(r)+str(c)+'=tkinter.Button(root, image=img, command=lambda: funny(str(po[0])))')
            exec('a'+str(r)+str(c)+'.grid(column=c,row=r)')
        else:
            po=(str(r)+str(c))
            exec('a'+str(r)+str(c)+'=tkinter.Button(root, image=img1, command=lambda: funny(str(po[0])))')
            exec('a'+str(r)+str(c)+'.grid(column=c,row=r)')

tkinter.mainloop()

