#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec  3 18:50:22 2016

@author: Pranavtadepalli
"""

# -*- coding: utf-8 -*-
"""
Created on Sat Dec  3 18:55:20 2016
@author: SRINIVAS
"""
import enchant
d = enchant.Dict("en_US")
#d.check("Hello")
in1=input('STRING\n')
ty=len(in1)
def posi(listy):
    t=[]
    for elem in range(len(listy)):
        t.append(''.join(listy))
        listy.pop()
  
    return t
done=0
final=[]
tray=0
loop=0
while done==0:
    loop=loop+1
    if loop==ty:
        break
    word=[]
    for elem in posi(list(in1)):
        if d.check(elem):
            if elem=='i' or elem=='a':
                tray=1
            if tray==1 or len(elem)!=1:
                word.append(elem)
        tray=0
    theone=''
    for ele in word:
        if len(ele)>len(theone):
            theone=ele
    print(theone)
    final.append(theone)
    in1=in1[len(theone):]
    if in1=='':
        done=1

print(' '.join(final))        
"""
for elem in list(in1):
    it=it+1
    listy.append(elem)
    if it!=1:
        if ''.join(listy) in words.words() and len(''.join(listy)):
            final.append(''.join(listy))
            listy=[]
        else:
            pass
"""
#print(final)